# this file for studying numby

## importing the needed libraries for data sceince

In [2]:
import numpy as np

## numby array

### definig an np array

In [3]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr=np.array((1,2,3,4),dtype=float) # we can specify the data type for the np array
arr2=np.array([list1,list2,list3]) 
arr3=np.ones((2,2)) # to make an nparray of ones with the shape (2,2) ((the shape is required)) 
arr4=np.zeros((3,2))
arr5=np.arange(10,20,2) # to make an np array start with 10 and ends with number less than 20 with steps of 2
arr6=np.linspace(0,30,10) # to make an np array consists of 10 numbers (start with 0 and ends with 30)
arr7=np.random.rand(2,3) # to make an np array with Random Numbers with the shape of (2,3) ((randint for random int not float))
arr8=arr4.reshape(2,3) # to change the shape of an array to new specify shape ((( new shape szie = old shape size )))
arr9=np.ones_like(arr8) # to make an np array of ones with (arr8) shape
arr10=np.zeros_like(arr9) # to make an np array of zeros with (arr9) shape
arr11=np.full(shape=(3,3,5),fill_value=8) # to make an np array with the shape of (3,3,5) and filled with the value 8
arr12=np.eye(5) # to make an array with the shape of (5,5) conssest of diagonal ones and filled with zeros ((diagonal matrix))

a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.array([[1],[2],[3],[4],[5]])
d=np.array([[10,20],[30,40],[50,60],[70,80]])
e=np.array([[3,1],[1,3]])
f=np.array([[3,5],[4,2]])

### array methodes

In [4]:
def describe(array):
    """ print a summary of an array """
    print(f"the array : {array}") 
    print(f"dimentions : {array.ndim}")      # the number for dimentions
    print(f"size : {array.size}")      # the size of the array
    print(f"shape : {array.shape}")     # the shape of the array (number of rows , number of colums)
    print(f"data type: {array.dtype}")     # the data type of the array
    print(f"data type name: {array.dtype.name}")     # the name of data type of the array
    print(f"data type: {array.astype(int)}")     # Convert an array to a different typ

#### examples

In [5]:
describe(arr)

the array : [1. 2. 3. 4.]
dimentions : 1
size : 4
shape : (4,)
data type: float64
data type name: float64
data type: [1 2 3 4]


In [6]:
describe(arr2)

the array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
dimentions : 2
size : 9
shape : (3, 3)
data type: int32
data type name: int32
data type: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
describe(arr3)

the array : [[1. 1.]
 [1. 1.]]
dimentions : 2
size : 4
shape : (2, 2)
data type: float64
data type name: float64
data type: [[1 1]
 [1 1]]


In [8]:
describe(arr4)

the array : [[0. 0.]
 [0. 0.]
 [0. 0.]]
dimentions : 2
size : 6
shape : (3, 2)
data type: float64
data type name: float64
data type: [[0 0]
 [0 0]
 [0 0]]


In [9]:
describe(arr5)

the array : [10 12 14 16 18]
dimentions : 1
size : 5
shape : (5,)
data type: int32
data type name: int32
data type: [10 12 14 16 18]


In [10]:
describe(arr6)

the array : [ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.         23.33333333 26.66666667 30.        ]
dimentions : 1
size : 10
shape : (10,)
data type: float64
data type name: float64
data type: [ 0  3  6 10 13 16 20 23 26 30]


In [186]:
describe(arr7)

the array : [[0.88980634 0.58741998 0.29023855]
 [0.54722195 0.69079044 0.34271892]]
dimentions : 2
size : 6
shape : (2, 3)
data type: float64
data type name: float64
data type: [[0 0 0]
 [0 0 0]]


In [187]:
describe(arr8)

the array : [[0. 0. 0.]
 [0. 0. 0.]]
dimentions : 2
size : 6
shape : (2, 3)
data type: float64
data type name: float64
data type: [[0 0 0]
 [0 0 0]]


In [188]:
describe(arr9)

the array : [[1. 1. 1.]
 [1. 1. 1.]]
dimentions : 2
size : 6
shape : (2, 3)
data type: float64
data type name: float64
data type: [[1 1 1]
 [1 1 1]]


In [189]:
describe(arr10)

the array : [[0. 0. 0.]
 [0. 0. 0.]]
dimentions : 2
size : 6
shape : (2, 3)
data type: float64
data type name: float64
data type: [[0 0 0]
 [0 0 0]]


In [190]:
describe(arr11)

the array : [[[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]]
dimentions : 3
size : 45
shape : (3, 3, 5)
data type: int32
data type name: int32
data type: [[[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]]


In [191]:
describe(arr12)

the array : [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
dimentions : 2
size : 25
shape : (5, 5)
data type: float64
data type name: float64
data type: [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### np array operation
the arays should have the same shape

#### element-wise operation

In [192]:
print(f"a = {a}")
print(f"b = {b}")
print(f'a+b = {a+b}') 
print(f'a-b = {a-b}')
print(f'a*b = {a*b}')
print(f'a/b = {a/b}')
print(f'a**b = {a**b}')


a = [1 2 3 4 5]
b = [ 6  7  8  9 10]
a+b = [ 7  9 11 13 15]
a-b = [-5 -5 -5 -5 -5]
a*b = [ 6 14 24 36 50]
a/b = [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
a**b = [      1     128    6561  262144 9765625]


#### scalar-wise operation

In [193]:
print(f"a = {a}")
print(f'a+10 = {a+10}') 
print(f'a-10 = {a-10}')
print(f'a*10 = {a*10}')
print(f'a/10 = {a/10}')
print(f'a**2 = {a**2}') # np.exp(a) 
print(f'sqrt(a) = {np.sqrt(a)}')
print(f'sin(a) = {np.sin(a)}')
print(f'cos(a) = {np.cos(a)}')
print(f'log(a) = {np.log(a)}')


a = [1 2 3 4 5]
a+10 = [11 12 13 14 15]
a-10 = [-9 -8 -7 -6 -5]
a*10 = [10 20 30 40 50]
a/10 = [0.1 0.2 0.3 0.4 0.5]
a**2 = [ 1  4  9 16 25]
sqrt(a) = [1.         1.41421356 1.73205081 2.         2.23606798]
sin(a) = [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos(a) = [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
log(a) = [0.         0.69314718 1.09861229 1.38629436 1.60943791]


#### dot product

In [194]:
print(f"e = {e}")
print(f"f = {f}")
print (f'Dot two array :\n{e.dot(f)}') # dot product of e and f 
print (f'Dot two array :\n{np.dot (e,f)}')  # dot product of e and f 
print (f'Sum of array f:{np.sum (f)}')
print (f'Add two array :\n{np.add(e,f)}')
print (f'Mean of array :\n{np.mean(e)}')
print (f'Matmul two array :\n{np.matmul(e,f)}') # dot product of e and f 
print (f'Multiply two array : \n {np.multiply(e,f)}') # multiply product of e and f(cross product)

e = [[3 1]
 [1 3]]
f = [[3 5]
 [4 2]]
Dot two array :
[[13 17]
 [15 11]]
Dot two array :
[[13 17]
 [15 11]]
Sum of array f:14
Add two array :
[[6 6]
 [5 5]]
Mean of array :
2.0
Matmul two array :
[[13 17]
 [15 11]]
Multiply two array : 
 [[9 5]
 [4 6]]


#### statistics over whole array 
Array-wise Aggregate Functions

In [195]:
print(f"a = {a}")
print(f"a max= {np.max(a)}")
print(f"a min= {np.min(a)}")
print(f"a sum= {np.sum(a)}")
print(f"a mean= {np.mean(a)}")
print(f"a median= {np.median(a)}")
print(f"a Standard deviation = {np.std(a)}")
print(f"a Correlation coefficient= {np.corrcoef(a)}")

a = [1 2 3 4 5]
a max= 5
a min= 1
a sum= 15
a mean= 3.0
a median= 3.0
a Standard deviation = 1.4142135623730951
a Correlation coefficient= 1.0


#### statistics by axis
axis =0 means columns
axis =1 means rows

In [196]:
print(d) 
print('d min (columns)', d.min(axis =0))
print('d min (rows)', d.min(axis = 1))
print('d max (columns)', d.max(axis =0))
print('d max (rows)', d.max(axis = 1))
print('d sum (columns)', d.sum (axis =0))
print('d sum (rows)', d.sum (axis = 1))
print('d mean (columns)', d.mean (axis =0))
print('d mean (rows)', d. mean (axis =1))

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
d min (columns) [10 20]
d min (rows) [10 30 50 70]
d max (columns) [70 80]
d max (rows) [20 40 60 80]
d sum (columns) [160 200]
d sum (rows) [ 30  70 110 150]
d mean (columns) [40. 50.]
d mean (rows) [15. 35. 55. 75.]


### comparsion

In [197]:
print(f"a == b : {a == b}") # Element-wise comparison
print(f"a< 2 : {a <= 2}")    # Element-wise comparison

print(f"np.array_equal(a, b)={np.array_equal(a, b)}") #Array-wise compariso




a == b : [False False False False False]
a< 2 : [ True  True False False False]
np.array_equal(a, b)=False


### Copying arrays

In [198]:
mycopy = a.view()   # Create a view of the array with the same data
np.copy(a)          # Create a copy of the array
mycopy = a.copy()   # Create a deep copy of the arra

### Sorting Arrays

In [199]:
a.sort()        #Sort an array
c.sort(axis=0)  #Sort the elements of an array's axis

### Subsetting, Slicing, Indexing

#### Subsetting

In [200]:
print(f"d =\n{d}")
print(f"d[1] = {d[1]}")      # Select the element with index
print(f"d[1,2] = {d[1,0]}")  # Select the element at row 1 column 0 (equivalent to d[1][0]) 

d =
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
d[1] = [30 40]
d[1,2] = 30


#### Sclicing

In [201]:
print(f"d =\n{d}")
print(f"d[0:4:2] =\n{d[0:4:2]}")    # Select the elements starting with index 0 ends at index less than 4 with steps of 2[starting index : end index : number of steps]
print(f"d[:4,1] =\n{d[:4,1]}")      # Select items at rows 0 to less than 4 in column 1
print(f"d[:2] =\n{d[:2]}")          # Select all items at row 2(equivalent to b[0:2, :])
print(f"d[2,...] =\n{d[2,...]}")    # Select all items at row 2(equivalent to b[2,:,:])
print(f"d[[::-1]] =\n{d[::-1]}")    # reversed array

d =
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
d[0:4:2] =
[[10 20]
 [50 60]]
d[:4,1] =
[20 40 60 80]
d[:2] =
[[10 20]
 [30 40]]
d[2,...] =
[50 60]
d[[::-1]] =
[[70 80]
 [50 60]
 [30 40]
 [10 20]]


#### Boolean Indexing

In [202]:
print(f"a =\n{a}")
print(f"a[a>2] =\n{a[a>2]}")    # Select that meets a certain criteria

a =
[1 2 3 4 5]
a[a>2] =
[3 4 5]


#### Fancy Indexing

In [203]:
print(f"d =\n{d}")
print(f"db[[1, 0, 1, 0],[0, 1, 2, 0]] =\n{d[[1, 0, 1, 0],[0, 1, 1, 0]]}")    # Select elements (1,0),(0,1),(1,1) and (0,0)
print(f"d[[1, 0, 1, 0]][:,[0,1,1,0]] =\n{d[[1, 0, 3, 2]][:,[0,1,1,0]]}")     # Select a subset of the matrix’s rows and columns

d =
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
db[[1, 0, 1, 0],[0, 1, 2, 0]] =
[30 20 40 10]
d[[1, 0, 1, 0]][:,[0,1,1,0]] =
[[30 40 40 30]
 [10 20 20 10]
 [70 80 80 70]
 [50 60 60 50]]


### Array Manipulation

#### Transposing Array
making long table into wide table and vice versa

In [204]:
print(f"d =\n{d}")
print(f"np.transpose(b) =\n{np.transpose(d)}") # Permute array dimensions
print(f"i.T  =\n{d.T}")            


d =
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
np.transpose(b) =
[[10 30 50 70]
 [20 40 60 80]]
i.T  =
[[10 30 50 70]
 [20 40 60 80]]


#### Changing Array Shape

In [205]:
print(f"arr7 =\n{arr7}")
print(f"arr7.ravel() =\n{arr7.ravel() }") #Flatten the array
print(f"arr7.reshape(3, 2) =\n{arr7.reshape(3, 2)}") #Reshape, but don’t change data
print(f"np.resize(3,5)= {arr7.resize((6,1))}") # change the array into a new array with shape (2,2)


arr7 =
[[0.88980634 0.58741998 0.29023855]
 [0.54722195 0.69079044 0.34271892]]
arr7.ravel() =
[0.88980634 0.58741998 0.29023855 0.54722195 0.69079044 0.34271892]
arr7.reshape(3, 2) =
[[0.88980634 0.58741998]
 [0.29023855 0.54722195]
 [0.69079044 0.34271892]]
np.resize(3,5)= None


#### adding /Removing Elements

In [206]:
print(f"arr = {arr}")
print(f"np.append(arr,5) = {np.append(arr,5)}") # add an item to array
print(f"np.insert(arr, 1, 5)  = {np.insert(arr, 1, 5) }") # Insert items into a specific location in an array (the array, the location, the item)
print(f"np.delete(arr,[1])= {np.delete(arr,[1])}") # delete an item in a specific location


arr = [1. 2. 3. 4.]
np.append(arr,5) = [1. 2. 3. 4. 5.]
np.insert(arr, 1, 5)  = [1. 5. 2. 3. 4.]
np.delete(arr,[1])= [1. 3. 4.]


#### Combining Arrays

In [207]:
print(f"e =\n{e}")
print(f"f =\n{f}")
print(f"np.concatenate((e,f),axis=0) =\n{np.concatenate((e,f),axis=0) }") # Concatenate arrays by axis 0 (column-wise)
print(f"np.concatenate((e,f),axis=1) =\n{np.concatenate((e,f),axis=1) }") # Concatenate arrays by axis 1 (row-wise)
print(f"np.vstack((e,f)) =\n{np.vstack((e,f))}") # Stack arrays vertically (row-wise)
print(f"np.r_[e,f] =\n{np.r_[e,f]}")             # Stack arrays vertically (row-wise)
print(f"np.column_stack((e,f)) =\n{np.column_stack((e,f))}") # Stack arrays horizontally (column-wise) 
print(f"np.hstack((e,f)) =\n{np.hstack((e,f))}")             # Stack arrays horizontally (column-wise)
print(f"np.c_[e,f] =\n{np.c_[e,f]}")                         # Stack arrays horizontally (column-wise)


e =
[[3 1]
 [1 3]]
f =
[[3 5]
 [4 2]]
np.concatenate((e,f),axis=0) =
[[3 1]
 [1 3]
 [3 5]
 [4 2]]
np.concatenate((e,f),axis=1) =
[[3 1 3 5]
 [1 3 4 2]]
np.vstack((e,f)) =
[[3 1]
 [1 3]
 [3 5]
 [4 2]]
np.r_[e,f] =
[[3 1]
 [1 3]
 [3 5]
 [4 2]]
np.column_stack((e,f)) =
[[3 1 3 5]
 [1 3 4 2]]
np.hstack((e,f)) =
[[3 1 3 5]
 [1 3 4 2]]
np.c_[e,f] =
[[3 1 3 5]
 [1 3 4 2]]


#### Splitting Arrays

In [127]:
print(f"d =\n{d}")
print(f"np.hsplit(d,1) =\n{np.hsplit(d,2)}")     # Split the array horizontally at givin index (return array)
print(f"np.hsplit(d,1)[1] =\n{np.hsplit(d,2)[0]}") 
print(f"np.hsplit(d,1)[2] =\n{np.hsplit(d,2)[1]}") 
print(f"np.vsplit(d,2) =\n{np.vsplit(d,2)}")     # Split the array vertically at the 2rd index
print(f"np.vsplit(d,2)[0] =\n{np.vsplit(d,2)[0]}")  
print(f"np.vsplit(d,2)[1] =\n{np.vsplit(d,2)[1]}")  

d =
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
np.hsplit(d,1) =
[array([[10],
       [30],
       [50],
       [70]]), array([[20],
       [40],
       [60],
       [80]])]
np.hsplit(d,1)[1] =
[[10]
 [30]
 [50]
 [70]]
np.hsplit(d,1)[2] =
[[20]
 [40]
 [60]
 [80]]
np.vsplit(d,2) =
[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]])]
np.vsplit(d,2)[0] =
[[10 20]
 [30 40]]
np.vsplit(d,2)[1] =
[[50 60]
 [70 80]]
